addons:
  apt:
    packages:
    - gdal-bin
    - postgresql-9.4-postgis-2.3
  postgresql: '9.4'
dist: trusty
install: pip install -r requirements.txt
language: python
python: 3.4
services:
- postgresql
script: python manage.py test
